<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fx_emp"
 *
 * Auto generated by Extension Builder 2019-02-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Employee Record',
    'description' => '',
    'category' => 'plugin',
    'author' => 'shovik',
    'author_email' => 'shovik@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
